config/routes.rb
Rails.application.routes.draw do
  resource :profile
  resources :entries
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  validates :weight, presence: true, numericality: {greater_than_or_equal_to: 0}
  validates :date_entered, presence: true
  before_validation :ensure_date_entered
  belongs_to :user

  attribute :date_entered, default: Date.today

  def ensure_date_entered
    self.date_entered = Date.today if date_entered.blank?
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # validates :height_inches, numericality: { greater_than_or_equal_to: 0 }
  has_many :entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate

  def authenticated?
    @authenticated
  end

  private

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      if username == ENV["USERNAME"] && password == ENV["PASSWORD"]
        @user = User.find_or_create_by!(username: username)
        return true
      end

      false
    end
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:destroy]
  def index
    @entries = @user.entries.order(date_entered: :desc)
  end

  def new
    @entry = Entry.new
  end

  def create
    @entry = @user.entries.new(entry_params)
    if @entry.save
      redirect_to entries_path, notice: "Entry added."
    else
      render :new
    end
  end

  def destroy
    @entry.destroy
    redirect_to entries_url, notice: "Entry was successfully destroyed."
  end

  private

  def set_entry
    @entry = @user.entries.find(params[:id])
  end

  def entry_params
    params.require(:entry).permit(:weight, :date_entered)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @max_weight = @user.entries.maximum(:weight)
    @min_weight = @user.entries.minimum(:weight)
    @current_weight = @user.entries.pluck(:weight).last
    @seven_day_average = @user.entries.where("date_entered >= ?", 7.days.ago).average(:weight)
    @thirty_day_average = @user.entries.where("date_entered >= ?", 30.days.ago).average(:weight)
    @twelve_month_average = @user.entries.where("date_entered >= ?", 12.months.ago).average(:weight)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/1/edit
  def edit
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to profile_path, notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_profile
    @profile = @user
  end

  # Only allow a list of trusted parameters through.
  def profile_params
    params.require(:user).permit(:height_inches)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entry_helper.rb
module EntryHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/entries/_form.html.erb
<%= form_with(model: entry, local: true) do |form| %>

  <div class="nes-container with-title">
    <p class="title">New Entry</p>
    <% if entry.errors.any? %>

      <div class="nes-text is-error">
        <%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:
      </div>
      <div class="nes-text is-error">
        <% entry.errors.full_messages.each do |message| %>
          <p><%= message %></p>
        <% end %>
      </div>

    <% end %>


    <div class="nes-field">
      <label for="name_field">Weight</label>
      <%= form.text_field :weight, class: "nes-input" %>
    </div>

    <div class="nes-field">
      <label for="name_field">Date</label>
      <%= form.text_field :date_entered, class: "nes-input" %>
    </div>

    <br>

    <button class="nes-btn is-primary" type="submit">
      Submit
    </button>




<% end %>


</div>

app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>

<h3 class="title">Weight Log</h3>
<%= link_to 'Log Weight', new_entry_path %>
<div class="nes-table-responsive">
  <table class="nes-table is-bordered is-centered" style="margin-left:auto;margin-right:auto;">
    <thead>
    <tr>
      <th>Weight</th>
      <th>Date Added</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.weight %></td>
        <td><%= entry.date_entered %></td>
        <td><%= link_to 'Destroy', entry_path(entry), method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/entries/new.html.erb
<div class="flex justify-center w-auto">
  <%= render 'form', entry: @entry %>
</div>

app/views/home/index.html.erb
<div class="nes-container with-title is-centered">
  <p class="title"><i class="nes-icon coin is-small"></i> Curent Score <i class="nes-icon coin is-small"></i></p>
  <%= @current_weight %> lbs
</div>
<br>
<div class="nes-container with-title is-centered">
  <p class="title"><i class="nes-icon trophy is-small"></i> High Score <i class="nes-icon trophy is-small"></i></p>
  <%= @min_weight %> lbs
</div>
<br>
<div class="nes-container with-title is-centered">
  <p class="title"><i class="nes-icon close is-small"></i> Low Score <i class="nes-icon close is-small"></i></p>
  <%= @max_weight %> lbs
</div>
<br>

<div class="nes-container with-title">
  <p class="title">7 days [<%=  number_with_precision(@seven_day_average,  precision: 2 )%>]</p>
  <%= line_chart @user.entries.group_by_day(:date_entered, last: 7, series: false).minimum(:weight),
                 colors: ["#92cc41"],
                 curve: false,
                 dataset:{pointStyle: "rect", borderWidth: 4, borderDash: [5, 5]},
                 library: {scales: {yAxes: [{ticks: {min: @min_weight}}]}}
  %>

</div>

<br>
<div class="nes-container with-title">
  <p class="title">30 days [<%=  number_with_precision(@thirty_day_average,  precision: 2 )%>]</p>

  <%= line_chart @user.entries.group_by_day(:date_entered, last: 30, series: false).minimum(:weight),
                 colors: ["#92cc41"],
                 curve: false,
                 dataset:{pointStyle: "rect", borderWidth: 4, borderDash: [5, 5]},
                 library: {scales: {yAxes: [{ticks: {min: @min_weight}}]}}
  %>

</div>

<br>
<div class="nes-container with-title">
  <p class="title">12 mo [<%=  number_with_precision(@twelve_month_average,  precision: 2 )%>]</p>
  <%= line_chart @user.entries.group_by_month(:date_entered, last: 12, series: false).minimum(:weight),
                 colors: ["#92cc41"],
                 curve: false,
                 dataset:{pointStyle: "rect", borderWidth: 4, borderDash: [5, 5]},
                 library: {pointStyle: "rect", scales: {yAxes: [{ticks: {min: @min_weight}}]}}
  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WeightTracker</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link href="https://fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet">
  <link href="https://unpkg.com/nes.css/css/nes.css" rel="stylesheet"/>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<nav style="text-align: center">

  <%= link_to "Start", root_url, class: 'nes-btn is-small' %>
  <%= link_to "Log", entries_path, class: "nes-btn is-success" %>
  <%= link_to "Profile", profile_path, class: "nes-btn is-primary" %>
  </div>
  </div>
</nav>

<div style="margin:auto; padding-top: 10px; max-width: 800px; text-align: center">
  <%= yield %>
</div>
</body>
</html>

app/views/profiles/_form.html.erb
<%= form_with(model: profile, url: profile_path, local: true) do |form| %>
  <div class="nes-container with-title">
    <p class="title">Edit Profile</p>
    <% if profile.errors.any? %>

      <div class="nes-text is-error">
        <%= pluralize(profile.errors.count, "error") %> prohibited this entry from being saved:
      </div>
      <div class="nes-text is-error">
        <% profile.errors.full_messages.each do |message| %>
          <p><%= message %></p>
        <% end %>
      </div>

    <% end %>


    <div class="nes-field">
      <label for="name_field">Height Inches</label>
      <%= form.text_field :height_inches, class: "nes-input" %>
    </div>

    <br>

    <button class="nes-btn is-primary" type="submit">
      Save
    </button>
    <%= link_to 'Cancel', profile_path, class: 'nes-btn' %>
  </div>

<% end %>

app/views/profiles/edit.html.erb
<%= render 'form', profile: @profile %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>
<p>Username: <%= @profile.username %></p>
<p>Height: <%= @profile.height_inches %> in</p>
<%= link_to 'Edit', edit_profile_path %>